1주차 코드 리뷰
FECrash/JavascriptCrash-Making pull request #14
Opened 2021-10-09 06:46 UTC by heejinna

2021-10-12 11:18 UTC, InSeong-So requested changes

2021-10-12 13:08 UTC, heejinna commented on sori/02_Functions/01.js
> +console.log(min, max);
네 맞아요! 사실 오늘 다시 spread operator로 리팩토링해보려 했는데😅 코멘트를 달아주셨네요
this를 바라보는 인자라서 지금같은 경우에는 0이나 null로 window를 바라보게 해서 계산합니다!
근데 배열이 커지거나 엔진에 따라 exception이 발생하기도 하고, spread operator를 사용한 방법이 더 개선된 방법이라 그쪽을 쓰는 게 더 나을 것 같습니다ㅎㅎㅎ

2021-10-12 13:10 UTC, heejinna commented on sori/02_Functions/01.js
> +console.log(reverse(arr));
네 sort 사용법을 제대로 익히고 싶어서 일부러 reverse 메서드를 안쓰고 해보았습니다!😄

2021-10-13 01:07 UTC, InSeong-So commented on sori/02_Functions/01.js
> +console.log(average(arr));
acc, cur은 MDN에 정의한 매개변수명으로 accumulator의 약자와 current의 약자로 사용하기에  널리 쓰여서 읽는데도 지장이 없기 때문입니다! 사실 이 누적치를 설명할 좋은 단어가 많이 없어서 그런 것도 있어요.

2021-10-14 03:09 UTC, HyoungDong commented on sori/02_Functions/01.js
> +
정렬된 배열에 한해서만 동작하는데 reverse 이름에 맞게
무작위 배열도 뒤집을 수 있는 기능으로도 한번 만들어 보시면 좋을것 같아요!

2021-10-14 03:54 UTC, heejinna commented on sori/02_Functions/01.js
> +
오 그부분은 생각을 못해 봤는데 알려주셔서 감사해요ㅎㅎ 오후에 한번 만들어보겠습니다!😊

2021-10-16 01:08 UTC, merged